#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'beautifulTriplets' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER d
#  2. INTEGER_ARRAY arr
#

def beautifulTriplets(d, arr):
    # Write your code here
    n = len(arr)
    count = 0
    # found = []
    
    # for i in range(n):
    #     for j in range(i+1, n):
    #         for k in range(j+1, n):
    #             if arr[j] -arr[i] == d and arr[k] - arr[j] == d:
    #                 tri = (arr[i],arr[j], arr[k])
                    
    #                 found.append(tri)
    #                 count += 1
    # return count  
    s = set(arr)
    for num in arr:
        if (num +d) in s and (num +d*2) in s:
            count += 1
    return count        

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    n = int(first_multiple_input[0])

    d = int(first_multiple_input[1])

    arr = list(map(int, input().rstrip().split()))

    result = beautifulTriplets(d, arr)

    fptr.write(str(result) + '\n')

    fptr.close()

