#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'bigSorting' function below.
#
# The function is expected to return a STRING_ARRAY.
# The function accepts STRING_ARRAY unsorted as parameter.
#

def bigSorting(unsorted):
    # Write your code here
    # m = len(unsorted)
    
    # for i in range(1,m):
    #     k = unsorted[i]
    #     j = i-1
    #     while j>= 0 and unsorted[j] > k:
    #         unsorted[j+1] = unsorted[j]
    #         j = j-1
    #     unsorted[j+1] = k
        
    # return unsorted  
      
    unsorted.sort(key=lambda x: (len(x), x))  # sort by length first, then lexicographically
    return unsorted
    
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    unsorted = []

    for _ in range(n):
        unsorted_item = input()
        unsorted.append(unsorted_item)

    result = bigSorting(unsorted)

    fptr.write('\n'.join(result))
    fptr.write('\n')

    fptr.close()
