#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'countingSort' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts INTEGER_ARRAY arr as parameter.
#

def countingSort(arr):
    # Write your code here
    # n = len(arr)
    
    # for i in range(1,n):
    #     k = arr[i]
    #     j = i-1
    #     while j >= 0 and arr[j] > k:
    #         arr[j+1] = arr[j]
    #         j = j - 1
    #     arr[j+1] = k
    # return arr       
    arr = sorted(arr)
    return arr
            

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    result = countingSort(arr)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
