#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'cutTheSticks' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts INTEGER_ARRAY arr as parameter.
#

def cutTheSticks(arr):
    # Write your code here
    result = []
    arr.sort()
    n = len(arr)
    # arr.sort()
    
    for i in range(n):
        if arr[i] > 0:
            result.append(n - i)   #how many sticks are remaining
            min_val = arr[i]       #current sticks length
            for j in range(i, n):  #cut by the min
                arr[j] -= min_val
            
    return result        

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    result = cutTheSticks(arr)

    fptr.write('\n'.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
