#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'pageCount' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER n
#  2. INTEGER p
#

def pageCount(n, p):
    # Write your code here
    # count_f = 0
    # count_b = 0
    # for i in range(len(n)):
    #     if n[i] == p:
    #         count_f += 1
    #     if n[i] != p:
    #         count_b += 1
    # return min(count_f,count_b)    
    front = p // 2  #how many turns from the first 
    
    back = n // 2 - p // 2 #how many turns from the back
    
    return min(front,back)

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    p = int(input().strip())

    result = pageCount(n, p)

    fptr.write(str(result) + '\n')

    fptr.close()
