#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'equalizeArray' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER_ARRAY arr as parameter.
#

def equalizeArray(arr):
    freq_count = {}
    for i in arr:
        if i in freq_count: 
            freq_count[i] += 1 # append on freq_count
        else:
            freq_count[i] = 1
    # return freq_count #{1: 2, 2: 2, 3: 4}        
    max_freq = max(freq_count.values())  # 4
    
    return len(arr) - max_freq          #8 - 4   
    
            
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    result = equalizeArray(arr)

    fptr.write(str(result) + '\n')

    fptr.close()
