#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'funnyString' function below.
#
# The function is expected to return a STRING.
# The function accepts STRING s as parameter.
#

def funnyString(s):
    # Write your code here
    code_s = [ord(c) for c in s]
    diff_s = []
    for i in range(len(code_s) - 1):
        minus_s = abs(code_s[i]- code_s[i+1])
        diff_s.append(minus_s)
        
    
    r = s[::-1] #reverse a str
    code_r = [ord(c) for c in r]
    diff_r = []
    
    for i in range(len(code_r) -1):
        minus_r = abs(code_r[i] - code_r[i+1])
        diff_r.append(minus_r)  
    
    if diff_s == diff_r:
        return "Funny"
    else:
        return "Not Funny"          

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    q = int(input().strip())

    for q_itr in range(q):
        s = input()

        result = funnyString(s)

        fptr.write(result + '\n')

    fptr.close()
