#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'gameOfThrones' function below.
#
# The function is expected to return a STRING.
# The function accepts STRING s as parameter.
#
from collections import Counter

def gameOfThrones(s):
    # Write your code here
    # from collections import Counter
    freq = Counter(s)
    
    odd_count = 0
    for val in freq.values():
        if val % 2 != 0:
            odd_count += 1
    if odd_count > 1:
        return "NO"
    else:
        return "YES"
                                

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = gameOfThrones(s)

    fptr.write(result + '\n')

    fptr.close()
