#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'insertionSort1' function below.
#
# The function accepts following parameters:
#  1. INTEGER n
#  2. INTEGER_ARRAY arr
#

def insertionSort1(n, arr):
    # Write your code here
    m = len(arr)
    k = arr[-1] # to store last element
    
    for i in range(m-2,-1,-1):
        if arr[i] > k:
            arr[i+1] = arr[i]
            print(*arr)    
        else:
            arr[i+1] = k
            print(*arr)
            break
    else:
        arr[0] = k
        print(*arr)    
if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    insertionSort1(n, arr)
