#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'makingAnagrams' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. STRING s1
#  2. STRING s2
#

def makingAnagrams(s1, s2):
    # Write your code here
    # res = []

    # for i in s1:
    #     if i not in s2:
    #         res.append(i)
    # re = []
    # for i in s2:
    #     if i not in s1:
    #         re.append(i)        
    # return ((len(res) + len(re)))
    
    freq1 = [0]*26 #26 is the alphabet english letter
    freq2 = [0]*26    

    for ch in s1:
        freq1[ord(ch)-ord('a')] += 1
    for ch in s2:
        freq2[ord(ch)-ord('a')] += 1
    delete = 0
    for i in range(26):
        delete += abs(freq1[i] - freq2[i])
    return delete

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s1 = input()

    s2 = input()

    result = makingAnagrams(s1, s2)

    fptr.write(str(result) + '\n')

    fptr.close()
