#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'migratoryBirds' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER_ARRAY arr as parameter.
#

def migratoryBirds(arr):
    # Write your code here
    freq = {}
    
    for bird in arr:
        freq[bird] = freq.get(bird, 0) + 1
    max_freq = max(freq.values())
    type = [bird for bird, count in freq.items() if count == max_freq]  # find all bird types with max frequency   
    return min(type)  #smallest type number.

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    arr_count = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    result = migratoryBirds(arr)

    fptr.write(str(result) + '\n')

    fptr.close()
