#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'plusMinus' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def plusMinus(arr):
    # Write your code here
    n = len(arr)   # set n as an len(array)
    
    posi_arr = [x for x in arr if x > 0]
    r = len(posi_arr) / n
    
    neg_arr = [x for x in arr if x < 0]
    neg = len(neg_arr) / n

    zero_arr = [x for x in arr if x == 0]
    zero = len(zero_arr) / n
                                                  #return → value function ke caller ko deta hai.
                                                  #print → value console pe dikhata hai.
    print("{:.6f}".format(r))        
    print("{:.6f}".format(neg))
    print("{:.6f}".format(zero))
    
if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    plusMinus(arr)
