#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'repeatedString' function below.
#
# The function is expected to return a LONG_INTEGER.
# The function accepts following parameters:
#  1. STRING s
#  2. LONG_INTEGER n
#

def repeatedString(s, n):
    # Write your code here
    # re = (s * ((n // len(s)) +1))[:n]
    
    # freq = {}
    # for i in re:
    #     if i in freq:
    #         freq[i] += 1
    #     else:
    #         freq[i] = 1
    # if "a" in freq:
    #     return freq["a"] 
    # else:
    #     return "0"             
    count_a = s.count("a")  #count 'a' in full str
    full_repeat = n // len(s)
    reminder = n % len(s)
    total_a = count_a * full_repeat + s[:reminder].count("a")
    return total_a

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    n = int(input().strip())

    result = repeatedString(s, n)

    fptr.write(str(result) + '\n')

    fptr.close()
