#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'timeConversion' function below.
#
# The function is expected to return a STRING.
# The function accepts STRING s as parameter.
#

def timeConversion(s):
    # Write your code here
    hh = int(s[:2])
    mm = s[3:5]
    ss = s[6:8]
    period = s[-2:]

    if period =="AM" and hh == 12:
        hh = 0
    if period == "PM" and hh != 12:
        hh += 12   
    return "{:02}:{:}:{:}".format(hh, mm, ss)
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = timeConversion(s)

    fptr.write(result + '\n')

    fptr.close()
